import { Work_Sans } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
const worksans = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar />
      <body className={worksans.className}>{children}</body>
    </html>
  );
}
