"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: leoni (https://sketchfab.com/leoni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hot-air-balloon-4b6c2073c9724440ae5da71ba19f05e8
Title: Hot Air Balloon
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import balloon2Model from "../assets/balloon2.glb";

export default function Balloon2(props) {
  const balloon2 = useGLTF(balloon2Model);
  const balloon2Ref = useRef();

  const initialY = 15.8;

  // Define the speed of the up and down movement
  const speed = 0.5;
  // Define the height range for the up and down movement
  const heightRange = 2.0;

  useFrame((state) => {
    const elapsedTime = state.clock.getElapsedTime();
    // Calculate the new Y position based on a sine wave
    const y = initialY + Math.sin(elapsedTime * speed) * heightRange;

    // Update the position of the balloon
    if (balloon2Ref.current) {
      balloon2Ref.current.position.set(-34, y, -25);
    }
  });

  return (
    <mesh ref={balloon2Ref} position={[-1, initialY, 0]} scale={[1, 1, 1]}>
      <primitive object={balloon2.scene} />
    </mesh>
  );
}

useGLTF.preload(balloon2Model);
