"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-island-88765d3c5db349e59c39cf9f592eba17
Title: Fantasy_Island
*/
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import fantasy from "../assets/fantasy_island.glb";
import { a } from "@react-spring/three";
import { useFrame, useThree } from "@react-three/fiber";

export default function FantasyIsland({
  isRotating,
  setIsRotating,
  setCurrentStage,
  ...props
}) {
  const islandRef = useRef();
  // Get access to the Three.js renderer and viewport
  const { gl, viewport } = useThree();
  const { nodes, materials } = useGLTF(fantasy);

  // Use a ref for the last mouse x position
  const lastX = useRef(0);
  // Use a ref for rotation speed
  const rotationSpeed = useRef(0);
  // Define a damping factor to control rotation damping
  const dampingFactor = 0.95;

  // Handle pointer (mouse or touch) down event
  const handlePointerDown = (event) => {
    event.stopPropagation();
    event.preventDefault();
    setIsRotating(true);

    // Calculate the clientX based on whether it's a touch event or a mouse event
    const clientX = event.touches ? event.touches[0].clientX : event.clientX;

    // Store the current clientX position for reference
    lastX.current = clientX;
  };

  // Handle pointer (mouse or touch) up event
  const handlePointerUp = (event) => {
    event.stopPropagation();
    event.preventDefault();
    setIsRotating(false);
  };

  // Handle pointer (mouse or touch) move event
  const handlePointerMove = (event) => {
    event.stopPropagation();
    event.preventDefault();
    if (isRotating) {
      // If rotation is enabled, calculate the change in clientX position
      const clientX = event.touches ? event.touches[0].clientX : event.clientX;

      // calculate the change in the horizontal position of the mouse cursor or touch input,
      // relative to the viewport's width
      const delta = (clientX - lastX.current) / viewport.width;

      // Update the island's rotation based on the mouse/touch movement
      islandRef.current.rotation.y += delta * 0.01 * Math.PI;

      // Update the reference for the last clientX position
      lastX.current = clientX;

      // Update the rotation speed
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  };

  // Handle keydown events
  const handleKeyDown = (event) => {
    // if (event.key === "ArrowLeft") {
    //   if (!isRotating) setIsRotating(true);

    //   islandRef.current.rotation.y += 0.005 * Math.PI;
    //   rotationSpeed.current = 0.007;
    // }
    if (event.key === "ArrowRight") {
      if (!isRotating) setIsRotating(true);

      islandRef.current.rotation.y -= 0.005 * Math.PI;
      rotationSpeed.current = -0.007;
    }
  };

  // Handle keyup events
  const handleKeyUp = (event) => {
    if (event.key === "ArrowLeft" || event.key === "ArrowRight") {
      setIsRotating(false);
    }
  };

  useEffect(() => {
    // Add event listeners for pointer and keyboard events
    const canvas = gl.domElement;
    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointermove", handlePointerMove);
    canvas.addEventListener("touchstart", handlePointerDown);
    canvas.addEventListener("touchend", handlePointerUp);
    canvas.addEventListener("touchmove", handlePointerMove);
    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);

    // Remove event listeners when component unmounts
    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointermove", handlePointerMove);
      canvas.removeEventListener("touchstart", handlePointerDown);
      canvas.removeEventListener("touchend", handlePointerUp);
      canvas.removeEventListener("touchmove", handlePointerMove);
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
    };
  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove]);

  // This function is called on each frame update
  useFrame(() => {
    // If not rotating, apply damping to slow down the rotation (smoothly)
    if (!isRotating) {
      // Apply damping factor
      rotationSpeed.current *= dampingFactor;

      // Stop rotation when speed is very small
      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }

      islandRef.current.rotation.y += rotationSpeed.current;
    } else {
      // When rotating, determine the current stage based on island's orientation
      const rotation = islandRef.current.rotation.y;

      /**
       * Normalize the rotation value to ensure it stays within the range [0, 2 * Math.PI].
       * The goal is to ensure that the rotation value remains within a specific range to
       * prevent potential issues with very large or negative rotation values.
       *  Here's a step-by-step explanation of what this code does:
       *  1. rotation % (2 * Math.PI) calculates the remainder of the rotation value when divided
       *     by 2 * Math.PI. This essentially wraps the rotation value around once it reaches a
       *     full circle (360 degrees) so that it stays within the range of 0 to 2 * Math.PI.
       *  2. (rotation % (2 * Math.PI)) + 2 * Math.PI adds 2 * Math.PI to the result from step 1.
       *     This is done to ensure that the value remains positive and within the range of
       *     0 to 2 * Math.PI even if it was negative after the modulo operation in step 1.
       *  3. Finally, ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI) applies another
       *     modulo operation to the value obtained in step 2. This step guarantees that the value
       *     always stays within the range of 0 to 2 * Math.PI, which is equivalent to a full
       *     circle in radians.
       */
      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
          setCurrentStage(4);
          break;
        case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
          setCurrentStage(2);
          break;
        case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
          setCurrentStage(1);
          break;
        default:
          setCurrentStage(null);
      }
    }
  });

  return (
    <a.group {...props} ref={islandRef}>
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials["rocks.003"]}
        position={[-48.606, 6.45, 13.052]}
        rotation={[-3.138, -0.513, 3.11]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials["tree bark"]}
        position={[-36.773, 6.538, 16.547]}
        rotation={[Math.PI, -1.083, Math.PI]}
      >
        <mesh
          geometry={nodes.Mball035.geometry}
          material={materials.leaves}
          position={[-6.085, 24.533, 16.858]}
          rotation={[-2.191, 0.507, 2.744]}
        />
        <mesh
          geometry={nodes.Mball036.geometry}
          material={materials.leaves}
          position={[7.701, 28.675, 12.685]}
          rotation={[0.367, 0.516, -0.032]}
        />
        <mesh
          geometry={nodes.Mball037.geometry}
          material={materials.leaves}
          position={[9.466, 27.167, 10.915]}
          rotation={[-1.132, -0.791, -1.186]}
        />
        <mesh
          geometry={nodes.Mball039.geometry}
          material={materials.leaves}
          position={[12.37, 17.614, 3.411]}
          rotation={[-2.785, -0.782, -2.116]}
        />
        <mesh
          geometry={nodes.Mball041.geometry}
          material={materials.leaves}
          position={[13.836, 15.788, 8.965]}
          rotation={[2.164, 0.538, -1.843]}
        />
        <mesh
          geometry={nodes.Mball042.geometry}
          material={materials["leaves.001"]}
          position={[11.774, 14.546, 11.037]}
          rotation={[-1.584, -0.419, -2.151]}
        />
        <mesh
          geometry={nodes.Mball043.geometry}
          material={materials.leaves}
          position={[13.97, 11.385, 9.784]}
          rotation={[-1.492, -0.595, -1.6]}
        />
        <mesh
          geometry={nodes.Mball044.geometry}
          material={materials["leaves.001"]}
          position={[5.534, 24.667, 14.265]}
          rotation={[0.135, -0.01, 0.104]}
        />
        <mesh
          geometry={nodes.Plane004.geometry}
          material={materials["tree bark"]}
          position={[-0.322, 17.856, 8.95]}
          rotation={[-1.261, 0.686, -0.012]}
        />
      </mesh>
      <group
        position={[-45.385, 8.643, -9.317]}
        rotation={[0.082, -1.052, 0.184]}
      >
        <mesh
          geometry={nodes.Cube012_1.geometry}
          material={materials["rocks.002"]}
        />
        <mesh
          geometry={nodes.Cube012_2.geometry}
          material={materials["rocks.003"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials["bark 2"]}
        position={[0.042, 8.557, 42.483]}
        rotation={[0.016, -0.851, -0.035]}
      >
        <mesh
          geometry={nodes.Plane008.geometry}
          material={materials["bark 2"]}
          position={[6.951, 18.382, 6.204]}
          rotation={[-2.812, 1.099, 2.25]}
        />
      </mesh>
      <group
        position={[-30.433, 8.865, 30.478]}
        rotation={[-1.41, -0.182, -2.308]}
      >
        <mesh
          geometry={nodes.Cube008_1.geometry}
          material={materials["rocks.002"]}
        />
        <mesh
          geometry={nodes.Cube008_2.geometry}
          material={materials["rocks.003"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials["rocks.001"]}
        position={[-54.103, 5.256, -5.999]}
        rotation={[-0.141, 0.541, 0.079]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials.pillar}
        position={[-52.458, 5.563, -6.101]}
        rotation={[0.201, -1.008, 0.162]}
      />
      <group
        position={[-46.367, 8.827, -31.152]}
        rotation={[0.066, 1.329, -0.124]}
      >
        <mesh
          geometry={nodes.Cube026_1.geometry}
          material={materials["rocks.003"]}
        />
        <mesh geometry={nodes.Cube026_2.geometry} material={materials.rocks} />
        <group position={[0, -2.99, 0]} rotation={[0, -1.271, 0]}>
          <mesh
            geometry={nodes.Cube028_1.geometry}
            material={materials["rocks.003"]}
          />
          <mesh
            geometry={nodes.Cube028_2.geometry}
            material={materials.rocks}
          />
        </group>
        <group position={[0, -1.933, 0]} rotation={[0, -1.271, 0]}>
          <mesh
            geometry={nodes.Cube029_1.geometry}
            material={materials["rocks.002"]}
          />
          <mesh
            geometry={nodes.Cube029_2.geometry}
            material={materials["rocks.003"]}
          />
        </group>
        <mesh
          geometry={nodes.Cube023.geometry}
          material={materials["rocks.002"]}
          position={[-1.408, -2.768, 0.446]}
          rotation={[0.048, -0.002, 0.116]}
        />
        <mesh
          geometry={nodes.Cube081.geometry}
          material={materials["rocks.002"]}
          position={[-1.274, -1.84, 0.11]}
          rotation={[0.02, -0.564, 0.193]}
        />
        <mesh
          geometry={nodes.Cube082.geometry}
          material={materials["rocks.002"]}
          position={[-0.55, -1.909, -1.205]}
          rotation={[2.437, 0.673, -2.143]}
        />
      </group>
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials.pillar}
        position={[-53.29, 5.396, -4.73]}
        rotation={[-0.091, 0.537, 0.174]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials.pillar}
        position={[-53.21, 5.427, -7.37]}
        rotation={[-0.047, 0.515, 0.184]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials.pillar}
        position={[-51.473, 5.423, 7.256]}
        rotation={[-0.078, 0.547, -0.073]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={materials["rocks.001"]}
        position={[-49.802, 5.513, 7.165]}
        rotation={[-0.022, -1.029, -0.083]}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={materials["rocks.001"]}
        position={[-50.659, 5.476, 8.53]}
        rotation={[-0.03, 0.535, 0.023]}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={materials.pillar}
        position={[-50.555, 5.456, 5.89]}
        rotation={[0.011, 0.509, 0.036]}
      />
      <mesh
        geometry={nodes.Cube030.geometry}
        material={materials.pillar}
        position={[-48.998, 5.489, 8.394]}
        rotation={[-0.009, 0.524, -0.028]}
      />
      <mesh
        geometry={nodes.Cube031.geometry}
        material={materials["rocks.001"]}
        position={[-47.382, 5.436, 8.281]}
        rotation={[-0.022, -1.029, -0.083]}
      />
      <mesh
        geometry={nodes.Cube032.geometry}
        material={materials.pillar}
        position={[-48.264, 5.476, 9.722]}
        rotation={[-0.03, 0.535, 0.023]}
      />
      <mesh
        geometry={nodes.Cube033.geometry}
        material={materials.pillar}
        position={[-48.069, 5.415, 6.987]}
        rotation={[0.011, 0.509, 0.036]}
      />
      <mesh
        geometry={nodes.Cube034.geometry}
        material={materials["rocks.001"]}
        position={[-53.221, 5.385, 10.09]}
        rotation={[-0.078, 0.547, -0.073]}
      />
      <mesh
        geometry={nodes.Cube035.geometry}
        material={materials.pillar}
        position={[-51.55, 5.475, 9.999]}
        rotation={[-0.022, -1.029, -0.083]}
      />
      <mesh
        geometry={nodes.Cube036.geometry}
        material={materials.pillar}
        position={[-52.407, 5.438, 11.365]}
        rotation={[-0.03, 0.535, 0.023]}
      />
      <mesh
        geometry={nodes.Cube037.geometry}
        material={materials.pillar}
        position={[-52.302, 5.418, 8.725]}
        rotation={[0.011, 0.509, 0.036]}
      />
      <mesh
        geometry={nodes.Cube038.geometry}
        material={materials.bark3}
        position={[44.725, 7.058, -24.956]}
        rotation={[-2.462, 0.262, -2.885]}
      >
        <mesh
          geometry={nodes.Plane013.geometry}
          material={materials.bark3}
          position={[3.991, 6.125, 14.281]}
          rotation={[-0.895, 0.55, 3.066]}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube039.geometry}
        material={materials["rocks.001"]}
        position={[-49.933, 6.439, -6.523]}
        rotation={[-0.187, 0.54, 0.308]}
      />
      <mesh
        geometry={nodes.Cube040.geometry}
        material={materials["rocks.001"]}
        position={[-48.383, 7.065, -6.642]}
        rotation={[0.519, -0.91, 0.459]}
      />
      <mesh
        geometry={nodes.Cube041.geometry}
        material={materials.pillar}
        position={[-49.115, 6.646, -5.267]}
        rotation={[-0.137, 0.545, 0.403]}
      />
      <mesh
        geometry={nodes.Cube042.geometry}
        material={materials.pillar}
        position={[-49.142, 6.874, -7.899]}
        rotation={[-0.131, 0.502, 0.335]}
      />
      <mesh
        geometry={nodes.Cube043.geometry}
        material={materials.pillar}
        position={[-47.349, 7.215, -5.511]}
        rotation={[-0.113, 0.561, 0.289]}
      />
      <mesh
        geometry={nodes.Cube044.geometry}
        material={materials.bones}
        position={[-16.769, 8.447, -43.704]}
        rotation={[-0.478, 1.205, 0.307]}
      />
      <mesh
        geometry={nodes.Cube045.geometry}
        material={materials.bones}
        position={[-16.495, 8.106, -45.35]}
        rotation={[-0.478, 1.205, 0.307]}
      />
      <mesh
        geometry={nodes.Cube046.geometry}
        material={materials.bones}
        position={[-15.888, 7.817, -46.724]}
        rotation={[-0.763, 1.3, 0.53]}
      />
      <mesh
        geometry={nodes.Cube047.geometry}
        material={materials.bones}
        position={[-16.055, 7.706, -48.502]}
        rotation={[-0.229, 1.382, -0.07]}
      />
      <mesh
        geometry={nodes.Cube048.geometry}
        material={materials.bones}
        position={[-16.103, 7.496, -51.289]}
        rotation={[0.193, 1.256, -0.479]}
      />
      <mesh
        geometry={nodes.Cube049.geometry}
        material={materials.bones}
        position={[-16.758, 7.038, -53.076]}
        rotation={[-0.229, 1.382, -0.07]}
      />
      <mesh
        geometry={nodes.Cube050.geometry}
        material={materials.bones}
        position={[-17.651, 6.186, -55.122]}
        rotation={[2.276, 1.457, -2.814]}
      />
      <mesh
        geometry={nodes.Cube051.geometry}
        material={materials.bones}
        position={[-18.599, 5.259, -57.149]}
        rotation={[-2.899, 1.507, 2.429]}
      />
      <mesh
        geometry={nodes.Cube052.geometry}
        material={materials.bones}
        position={[-20.753, 4.338, -61.366]}
        rotation={[2.257, 1.473, -2.796]}
      />
      <mesh
        geometry={nodes.Cube053.geometry}
        material={materials.bones}
        position={[-18.889, 5.102, -59.292]}
        rotation={[1.392, 1.447, -1.772]}
      />
      <mesh
        geometry={nodes.Cube054.geometry}
        material={materials.bones}
        position={[-21.258, 4.099, -62.843]}
        rotation={[1.908, 1.409, -2.273]}
      />
      <mesh
        geometry={nodes.Cube055.geometry}
        material={materials.bones}
        position={[-22.889, 3.393, -64.117]}
        rotation={[-2.59, 1.403, 2.409]}
      />
      <mesh
        geometry={nodes.Cube056.geometry}
        material={materials.bones}
        position={[-28.91, 5.731, -48.79]}
        rotation={[0.842, -1.493, 0.883]}
      />
      <mesh
        geometry={nodes.Cube057.geometry}
        material={materials.bones}
        position={[-27.967, 6.493, -46.186]}
        rotation={[0.608, -1.307, 0.515]}
      />
      <mesh
        geometry={nodes.Cube058.geometry}
        material={materials.bones}
        position={[-26.392, 7.093, -44.334]}
        rotation={[0.608, -1.307, 0.515]}
      />
      <mesh
        geometry={nodes.Cube059.geometry}
        material={materials.bones}
        position={[-33.086, 3.332, -56.377]}
        rotation={[2.509, -1.458, 2.545]}
      />
      <mesh
        geometry={nodes.Cube061.geometry}
        material={materials.rocks}
        position={[55.1, 6.662, -0.399]}
        rotation={[-0.058, -0.917, -0.173]}
      />
      <mesh
        geometry={nodes.Cube062.geometry}
        material={materials["rocks.001"]}
        position={[55.284, 6.013, 3.254]}
        rotation={[-3.075, -0.449, -2.753]}
      />
      <mesh
        geometry={nodes.Cube063.geometry}
        material={materials["rocks.001"]}
        position={[52.433, 6.248, 1.321]}
        rotation={[3.138, -1.228, 2.979]}
      />
      <mesh
        geometry={nodes.Cube064.geometry}
        material={materials["rocks.001"]}
        position={[6.394, 17.958, -33.249]}
        rotation={[-0.344, -0.726, -0.059]}
      />
      <mesh
        geometry={nodes.Cube065.geometry}
        material={materials.rocks}
        position={[3.039, 17.013, -33.222]}
        rotation={[3.103, -0.354, 0.267]}
      />
      <mesh
        geometry={nodes.Cube066.geometry}
        material={materials.rocks}
        position={[32.018, 8.51, 32.329]}
        rotation={[3.044, -1.22, 3.101]}
      />
      <mesh
        geometry={nodes.Cube067.geometry}
        material={materials["rocks.001"]}
        position={[31.028, 7.173, 36.961]}
        rotation={[0.972, 1.311, 2.254]}
      />
      <mesh
        geometry={nodes.Cube070.geometry}
        material={materials.bark3}
        position={[5.527, 29.975, 21.199]}
        rotation={[-2.333, 0.617, -2.679]}
      />
      <group position={[2.042, 61.728, -0.692]}>
        <mesh
          geometry={nodes.Cylinder003_1.geometry}
          material={materials["rocks.002"]}
        />
        <mesh
          geometry={nodes.Cylinder003_2.geometry}
          material={materials["rocks.003"]}
        />
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials["rocks.003"]}
          position={[-4.584, -2.078, 1.892]}
          rotation={[0.01, 0.363, -0.005]}
        />
        <group
          position={[-0.758, 5.069, -3.95]}
          rotation={[3.14, 0.016, -3.113]}
        >
          <mesh
            geometry={nodes.Cube005_1.geometry}
            material={materials["rocks.002"]}
          />
          <mesh
            geometry={nodes.Cube005_2.geometry}
            material={materials["rocks.003"]}
          />
        </group>
        <group position={[-2.21, 5.019, 3.348]} rotation={[0, -0.754, 0]}>
          <mesh
            geometry={nodes.Cube004_1.geometry}
            material={materials["rocks.002"]}
          />
          <mesh
            geometry={nodes.Cube004_2.geometry}
            material={materials["rocks.003"]}
          />
        </group>
        <group
          position={[-3.947, 5.077, -0.736]}
          rotation={[Math.PI, -1.166, Math.PI]}
        >
          <mesh
            geometry={nodes.Cube003_1.geometry}
            material={materials["rocks.002"]}
          />
          <mesh
            geometry={nodes.Cube003_2.geometry}
            material={materials["rocks.003"]}
          />
        </group>
        <group
          position={[-3.977, 0.769, 0.025]}
          rotation={[Math.PI, -1.206, Math.PI]}
        >
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials["rocks.002"]}
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials["rocks.003"]}
          />
        </group>
        <group position={[-5.53, -3.537, 0.348]} rotation={[0, 0.486, 0]}>
          <mesh
            geometry={nodes.Cube002_1.geometry}
            material={materials["rocks.002"]}
          />
          <mesh
            geometry={nodes.Cube002_2.geometry}
            material={materials["rocks.003"]}
          />
        </group>
        <group position={[-5.715, -3.905, 0.058]} rotation={[0, 0.486, 0]}>
          <mesh
            geometry={nodes.Cube001_1.geometry}
            material={materials["rocks.002"]}
          />
          <mesh
            geometry={nodes.Cube001_2.geometry}
            material={materials["rocks.003"]}
          />
        </group>
        <group position={[-5.963, -4.267, -0.377]} rotation={[0, 0.486, 0]}>
          <mesh
            geometry={nodes.Cube016_1.geometry}
            material={materials["rocks.002"]}
          />
          <mesh
            geometry={nodes.Cube016_2.geometry}
            material={materials["rocks.003"]}
          />
        </group>
        <mesh
          geometry={nodes.Cube008.geometry}
          material={materials["rocks.002"]}
          position={[-6.568, -4.694, -0.733]}
          rotation={[0, 0.486, 0]}
        />
        <mesh
          geometry={nodes.Cube010.geometry}
          material={nodes.Cube010.material}
          position={[-6.359, -1.567, 1.896]}
          rotation={[-0.07, -1.516, -0.15]}
        />
        <mesh
          geometry={nodes.Cube011.geometry}
          material={nodes.Cube011.material}
          position={[-5.778, -0.825, 3.238]}
          rotation={[-0.596, -1.05, -2.186]}
        />
        <mesh
          geometry={nodes.Cube015.geometry}
          material={materials.bark3}
          position={[12.723, -4.864, 6.27]}
          rotation={[Math.PI, -0.895, Math.PI]}
        />
        <mesh
          geometry={nodes.Cylinder001.geometry}
          material={materials["rocks.002"]}
          position={[0.026, 0.19, -0.058]}
        />
        <mesh
          geometry={nodes.Cylinder003.geometry}
          material={materials["rocks.002"]}
          position={[-4.057, 3.845, -0.711]}
          rotation={[0.04, 0.009, 0.091]}
        />
        <mesh
          geometry={nodes.Cylinder005.geometry}
          material={materials["rocks.001"]}
          position={[-2.202, 3.846, 3.322]}
          rotation={[3.131, -1.239, -3.115]}
        />
        <mesh
          geometry={nodes.Cylinder010.geometry}
          material={materials["rocks.002"]}
          position={[-0.707, 3.809, -4.11]}
          rotation={[0.11, -1.203, 0.194]}
        />
        <mesh
          geometry={nodes.Circle_1.geometry}
          material={materials["rocks.002"]}
        />
        <mesh
          geometry={nodes.Circle_2.geometry}
          material={materials["rocks.003"]}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials.pillar}
        position={[-48.335, 5.707, 2.827]}
        rotation={[0.082, -0.021, 0.005]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials.pillar}
        position={[-41.547, 6.947, 26.178]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials.pillar}
        position={[-52.494, 6.064, -20.84]}
        rotation={[0.01, -0.018, 0.045]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials["Material.004"]}
        position={[29.339, 16.048, -89.902]}
        rotation={[0, -0.086, 0]}
      >
        <group
          position={[0.313, 38.688, 0.128]}
          rotation={[0.084, 0.653, -0.085]}
        >
          <mesh
            geometry={nodes.Cube078_1.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            geometry={nodes.Cube078_2.geometry}
            material={materials.emission}
          />
        </group>
        <mesh
          geometry={nodes.Cube069.geometry}
          material={materials["Material.004"]}
          position={[1.522, 32.199, 4.473]}
          rotation={[0.092, -0.987, 1.592]}
        />
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials.emission}
          position={[0.188, 12.681, 0.216]}
          rotation={[0, 0.638, 0]}
        />
      </mesh>
      <mesh
        geometry={nodes.Icosphere002.geometry}
        material={materials.rocks}
        position={[-33.218, 10.751, 17.88]}
        rotation={[0.125, 0.119, 0.25]}
      />
      <mesh
        geometry={nodes.Icosphere003.geometry}
        material={materials["rocks.001"]}
        position={[-18.065, 12.48, 34.021]}
        rotation={[2.914, -1.179, 2.858]}
      />
      <mesh
        geometry={nodes.Icosphere004.geometry}
        material={nodes.Icosphere004.material}
        position={[-10.333, 10.844, 33.594]}
        rotation={[1.157, -1.241, -0.849]}
      />
      <mesh
        geometry={nodes.Icosphere005.geometry}
        material={materials["rocks.001"]}
        position={[-31.641, 12.833, 10.918]}
        rotation={[0, 1.234, 0]}
      />
      <mesh
        geometry={nodes.Icosphere006.geometry}
        material={materials["rocks.001"]}
        position={[38.682, 9.513, -23.912]}
        rotation={[0.338, 0.001, 1.147]}
      />
      <mesh
        geometry={nodes.Icosphere007.geometry}
        material={materials.rocks}
        position={[39.922, 11.005, -17.435]}
        rotation={[0.135, -0.398, 0.317]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["bark 2"]}
        position={[-40.323, 8.363, -17.777]}
        rotation={[2.348, -1.164, 2.193]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["bark 2"]}
        position={[4.8, 53.747, 12.318]}
        rotation={[0.534, -0.92, 0.322]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials["tree bark"]}
        position={[-22.827, 25.683, -0.951]}
        rotation={[-0.051, 0.401, 0.512]}
      />
      <mesh
        geometry={nodes.Plane009.geometry}
        material={materials.bark3}
        position={[19.64, 6.475, 46.29]}
        rotation={[2.982, 0.351, -2.981]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={materials.bark3}
        position={[18.027, 6.475, 46.136]}
        rotation={[0.171, -0.508, 0.189]}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={materials["bark 2"]}
        position={[-8.089, 47.747, 9.648]}
        rotation={[-3.136, -0.4, 2.456]}
      />
      <mesh
        geometry={nodes.Plane012.geometry}
        material={materials["bark 2"]}
        position={[12.121, 56.291, 0.638]}
        rotation={[2.491, -1.011, -3.121]}
      />
      <group position={[-14.879, -3.715, 61.952]}>
        <mesh
          geometry={nodes.Plane014_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Plane014_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane015.geometry}
        material={materials["tree bark"]}
        position={[24.85, 8.315, -40.216]}
        rotation={[0.367, -1.162, 0.175]}
      />
      <mesh
        geometry={nodes.Plane016.geometry}
        material={materials["bark 2"]}
        position={[2.393, 39.328, -16.989]}
        rotation={[1.372, -1.405, 1.614]}
      />
      <mesh
        geometry={nodes.Mball021.geometry}
        material={materials.leaves}
        position={[20.941, 55.434, 32.738]}
      />
      <mesh
        geometry={nodes.Mball019.geometry}
        material={materials["leaves.002"]}
        position={[2.522, 28.154, 58.03]}
        rotation={[0.159, -0.15, 0.119]}
      />
      <mesh
        geometry={nodes.Mball002.geometry}
        material={materials["leaves.003"]}
        position={[2.848, 28.6, 49.581]}
        rotation={[-1.066, -0.957, -0.762]}
      />
      <mesh
        geometry={nodes.Mball003.geometry}
        material={materials["leaves.002"]}
        position={[4.118, 22.589, 50.387]}
        rotation={[1.621, 0.377, -1.148]}
      />
      <mesh
        geometry={nodes.Mball004.geometry}
        material={materials["leaves.002"]}
        position={[-11.692, 35.919, 50.993]}
        rotation={[-1, 0.573, 1.512]}
      />
      <mesh
        geometry={nodes.Mball007.geometry}
        material={materials["leaves.002"]}
        position={[5.287, 51.559, 23.934]}
        rotation={[-0.101, -1.084, 0.214]}
      />
      <mesh
        geometry={nodes.Mball010.geometry}
        material={materials["Material.007"]}
        position={[-11.518, 59.082, 15.713]}
        rotation={[2.717, -1.459, 1.823]}
      />
      <mesh
        geometry={nodes.Mball011.geometry}
        material={materials["Material.007"]}
        position={[-8.444, 55.726, 14.385]}
        rotation={[-0.648, -0.495, -2.269]}
      />
      <mesh
        geometry={nodes.Mball013.geometry}
        material={materials["Material.007"]}
        position={[-17.583, 58.315, 14.219]}
        rotation={[-3.081, -0.788, 1.488]}
      />
      <mesh
        geometry={nodes.Mball014.geometry}
        material={materials["Material.007"]}
        position={[-16.128, 56.62, 13.599]}
        rotation={[3.112, -0.776, 2.197]}
      />
      <mesh
        geometry={nodes.Mball112.geometry}
        material={materials.leaves}
        position={[-6.019, 67.897, 7.093]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials.bones}
        position={[-31.841, 4.108, -53.714]}
        rotation={[2.509, -1.458, 2.545]}
      />
      <mesh
        geometry={nodes.Mball081.geometry}
        material={materials.leaves}
        position={[19.069, 68.409, -9.042]}
      />
      <mesh
        geometry={nodes.Mball001.geometry}
        material={materials.leaves}
        position={[-0.816, 79.72, -9.864]}
        rotation={[-0.577, -0.722, 0.778]}
      />
      <mesh
        geometry={nodes.Mball005.geometry}
        material={materials["leaves.002"]}
        position={[57.289, 33.751, -24.118]}
        rotation={[-1.394, -0.76, -1.294]}
      />
      <mesh
        geometry={nodes.Mball006.geometry}
        material={materials["leaves.002"]}
        position={[51.471, 22.021, -35.509]}
        rotation={[-0.491, 0.072, 0.01]}
      />
      <mesh
        geometry={nodes.Mball008.geometry}
        material={materials["leaves.002"]}
        position={[50.744, 22.438, -28.915]}
        rotation={[-1.18, -1.427, -1.57]}
      />
      <mesh
        geometry={nodes.Mball009.geometry}
        material={materials["leaves.003"]}
        position={[-0.504, 59.354, -19.589]}
        rotation={[-2.421, 0.558, 2.546]}
      />
      <mesh
        geometry={nodes.Mball012.geometry}
        material={materials["leaves.003"]}
        position={[-0.485, 58.539, -22.533]}
        rotation={[2.847, 0.954, 3.095]}
      />
      <mesh
        geometry={nodes.Mball015.geometry}
        material={materials["leaves.003"]}
        position={[-0.485, 55.804, -19.765]}
        rotation={[-2.732, 0.517, 2.522]}
      />
      <mesh
        geometry={nodes.Mball016.geometry}
        material={materials["leaves.002"]}
        position={[-0.067, 53.016, -26.68]}
        rotation={[-1.978, -1.374, -1.621]}
      />
      <mesh
        geometry={nodes.Mball017.geometry}
        material={materials["leaves.002"]}
        position={[1.554, 51.519, -29.068]}
        rotation={[-0.655, -0.464, -0.103]}
      />
      <mesh
        geometry={nodes.Mball018.geometry}
        material={materials["leaves.002"]}
        position={[-0.936, 51.328, -30.736]}
        rotation={[-2.153, 1.373, 1.615]}
      />
      <mesh
        geometry={nodes.Mball020.geometry}
        material={materials["leaves.002"]}
        position={[5.22, 50.188, -26.288]}
        rotation={[2.044, 0.719, -2.087]}
      />
      <mesh
        geometry={nodes.Mball022.geometry}
        material={materials["leaves.003"]}
        position={[5.413, 48.525, -24.62]}
        rotation={[0.126, -0.155, -1.168]}
      />
      <mesh
        geometry={nodes.Mball023.geometry}
        material={materials["leaves.002"]}
        position={[-44.166, 23.613, -26.873]}
        rotation={[0.509, -0.275, 0.524]}
      />
      <mesh
        geometry={nodes.Mball024.geometry}
        material={materials["leaves.003"]}
        position={[-41.94, 23.127, -28.067]}
        rotation={[2.602, -0.817, -2.696]}
      />
      <mesh
        geometry={nodes.Mball025.geometry}
        material={materials["leaves.002"]}
        position={[-45.578, 19.915, -31.074]}
        rotation={[2.574, 0.521, 2.974]}
      />
      <mesh
        geometry={nodes.Mball026.geometry}
        material={materials["leaves.003"]}
        position={[-37.652, 22.544, -23.922]}
        rotation={[-2.907, -0.512, -2.285]}
      />
      <mesh
        geometry={nodes.Mball027.geometry}
        material={materials["leaves.003"]}
        position={[-37.696, 21.757, -21.922]}
        rotation={[2.668, 1.189, -1.705]}
      />
      <mesh
        geometry={nodes.Mball028.geometry}
        material={materials.leaves}
        position={[-48.21, 34.645, -18.116]}
        rotation={[-2.813, -0.657, -2.765]}
      />
      <mesh
        geometry={nodes.Mball029.geometry}
        material={materials.leaves}
        position={[-48.182, 31.723, -21.881]}
        rotation={[2.766, 0.414, -3.089]}
      />
      <mesh
        geometry={nodes.Mball030.geometry}
        material={materials["leaves.003"]}
        position={[-48.569, 29.148, -16.588]}
        rotation={[2.766, 0.414, -3.089]}
      />
      <mesh
        geometry={nodes.Mball031.geometry}
        material={materials["leaves.002"]}
        position={[42.015, 27.132, -32.638]}
        rotation={[-0.448, -0.174, 0.647]}
      />
      <mesh
        geometry={nodes.Mball032.geometry}
        material={materials["leaves.002"]}
        position={[41.075, 22.284, -29.996]}
        rotation={[0.211, -0.786, 0.388]}
      />
      <mesh
        geometry={nodes.Mball033.geometry}
        material={materials["leaves.002"]}
        position={[38.939, 22.136, -25.474]}
        rotation={[-2.936, -0.905, 2.611]}
      />
      <mesh
        geometry={nodes.Mball034.geometry}
        material={materials["rocks.001"]}
        position={[37.741, 6.022, 27.39]}
        rotation={[-0.27, -0.961, -0.345]}
      />
      <mesh
        geometry={nodes.Mball038.geometry}
        material={materials.leaves}
        position={[-46.027, 27.345, 23.928]}
        rotation={[-2.574, 0.08, 3.039]}
      />
      <mesh
        geometry={nodes.Mball040.geometry}
        material={materials["leaves.001"]}
        position={[-43.365, 26.077, 24.485]}
        rotation={[2.998, 0.985, -2.322]}
      />
      <mesh
        geometry={nodes.Mball045.geometry}
        material={materials["leaves.003"]}
        position={[13.945, 22.866, 41.17]}
        rotation={[-0.216, 0.431, 0.043]}
      />
      <mesh
        geometry={nodes.Mball046.geometry}
        material={materials["leaves.002"]}
        position={[16.523, 21.241, 42.437]}
        rotation={[-1.436, 0.109, -0.726]}
      />
      <mesh
        geometry={nodes.Mball047.geometry}
        material={materials["leaves.002"]}
        position={[16.593, 24.556, 48.199]}
        rotation={[-0.562, -0.745, -0.14]}
      />
      <mesh
        geometry={nodes.Mball048.geometry}
        material={materials["leaves.002"]}
        position={[15.445, 16.195, 40.844]}
        rotation={[-0.112, 0.74, -1.163]}
      />
      <mesh
        geometry={nodes.Mball049.geometry}
        material={materials["leaves.002"]}
        position={[14.994, 15.24, 40.897]}
        rotation={[1.199, 0.303, -2.359]}
      />
      <mesh
        geometry={nodes.Mball050.geometry}
        material={materials["leaves.002"]}
        position={[23.048, 32.526, 45.315]}
        rotation={[-0.193, -0.929, 0.533]}
      />
      <mesh
        geometry={nodes.Mball051.geometry}
        material={materials["leaves.002"]}
        position={[30.226, 27.806, 46.92]}
        rotation={[-2.742, 0.01, -2.402]}
      />
      <mesh
        geometry={nodes.Mball052.geometry}
        material={materials["leaves.002"]}
        position={[34.743, 26.469, 48.565]}
        rotation={[-2.197, -0.927, -1.513]}
      />
      <mesh
        geometry={nodes.Mball053.geometry}
        material={materials["leaves.002"]}
        position={[32.116, 24.912, 51.326]}
        rotation={[0.421, -0.811, 1.16]}
      />
      <mesh
        geometry={nodes.Mball054.geometry}
        material={materials["leaves.003"]}
        position={[29.243, 21.646, 52.717]}
        rotation={[0.245, -0.686, 0.619]}
      />
      <mesh
        geometry={nodes.Mball055.geometry}
        material={materials["leaves.003"]}
        position={[25.583, 19.772, 52.906]}
        rotation={[1.834, -0.759, 1.592]}
      />
      <mesh
        geometry={nodes.Mball056.geometry}
        material={materials["leaves.002"]}
        position={[17.946, 24.091, -47.066]}
        rotation={[-0.448, -0.174, 0.647]}
      />
      <mesh
        geometry={nodes.Mball057.geometry}
        material={materials["leaves.002"]}
        position={[18.741, 21.744, -48.461]}
        rotation={[2.425, -1.269, -2.633]}
      />
      <mesh
        geometry={nodes.Mball058.geometry}
        material={materials["leaves.002"]}
        position={[15.01, 20.511, -49.615]}
        rotation={[-1.473, 0.958, 1.164]}
      />
      <mesh
        geometry={nodes.Mball059.geometry}
        material={materials["leaves.004"]}
        position={[25.706, 21.272, -46.526]}
        rotation={[-1.81, -0.349, -0.802]}
      />
      <mesh
        geometry={nodes.Mball060.geometry}
        material={materials["leaves.002"]}
        position={[21.935, 34.64, -39.17]}
        rotation={[-0.1, -0.247, 0.793]}
      />
      <mesh
        geometry={nodes.Mball061.geometry}
        material={materials.leaves}
        position={[-36.562, 45.408, 0.808]}
        rotation={[-2.477, 0.767, 2.214]}
      />
      <mesh
        geometry={nodes.Mball062.geometry}
        material={materials.leaves}
        position={[-40.591, 38.662, 2.951]}
        rotation={[-0.891, 0.336, 1.541]}
      />
      <mesh
        geometry={nodes.Mball063.geometry}
        material={materials["leaves.003"]}
        position={[-36.767, 35.315, -1.307]}
        rotation={[-1.69, -0.507, 0.028]}
      />
      <mesh
        geometry={nodes.Mball064.geometry}
        material={materials["Material.007"]}
        position={[-16.808, 58.693, 11.968]}
        rotation={[2.636, -0.084, 2.244]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials["leaves.002"]}
        position={[-59.556, 4.693, -17.777]}
        rotation={[-1.661, -0.873, -1.907]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials["leaves.002"]}
        position={[-36.792, 4.023, -47.22]}
        rotation={[-1.205, -0.237, -0.644]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials["leaves.002"]}
        position={[-57.398, 4.874, -17.055]}
        rotation={[-1.185, 0.51, -0.346]}
      />
      <mesh
        geometry={nodes.Plane017.geometry}
        material={materials.leaves}
        position={[-49.084, 6.079, -0.629]}
        rotation={[-1.3, 0.186, -0.188]}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={materials["leaves.002"]}
        position={[-49.652, 5.187, 11.04]}
        rotation={[-2.172, 0.055, 1.966]}
      />
      <mesh
        geometry={nodes.Plane019.geometry}
        material={materials.leaves}
        position={[-0.711, 38.829, -18.658]}
        rotation={[-1.262, -0.402, -0.791]}
      />
      <mesh
        geometry={nodes.Plane020.geometry}
        material={materials.leaves}
        position={[0.854, 19.845, -30.711]}
        rotation={[-1.8, -0.439, -0.957]}
      />
      <mesh
        geometry={nodes.Plane021.geometry}
        material={materials["leaves.003"]}
        position={[-21.012, 6.564, -45.429]}
        rotation={[-1.073, -0.447, -1.041]}
      />
      <mesh
        geometry={nodes.Plane022.geometry}
        material={materials.leaves}
        position={[-30.733, 4.785, -48.868]}
        rotation={[-1.781, -0.763, -1.993]}
      />
      <mesh
        geometry={nodes.Plane023.geometry}
        material={materials["leaves.002"]}
        position={[-15.582, 5.201, -57.266]}
        rotation={[-1.702, -0.399, -1.885]}
      />
      <mesh
        geometry={nodes.Plane024.geometry}
        material={materials["leaves.002"]}
        position={[-19.759, 3.913, -63.351]}
        rotation={[-1.803, -0.384, -1.716]}
      />
      <mesh
        geometry={nodes.Plane025.geometry}
        material={materials.leaves}
        position={[42.407, 7.061, -31.44]}
        rotation={[-1.645, -0.171, -1.951]}
      />
      <mesh
        geometry={nodes.Plane026.geometry}
        material={materials["leaves.002"]}
        position={[58.761, 3.089, 2.051]}
        rotation={[-0.889, 0.341, -1.446]}
      />
      <mesh
        geometry={nodes.Plane027.geometry}
        material={materials["leaves.002"]}
        position={[54.077, 8.759, 2.932]}
        rotation={[-0.526, 0.012, -1.172]}
      />
      <mesh
        geometry={nodes.Cube060.geometry}
        material={materials["rocks.001"]}
        position={[19.875, 6.246, 48.287]}
        rotation={[0.217, 0.17, -3.111]}
      />
      <mesh
        geometry={nodes.Plane028.geometry}
        material={materials["leaves.003"]}
        position={[17.677, 6.267, 48.927]}
        rotation={[-0.689, -0.477, -1.162]}
      />
      <mesh
        geometry={nodes.Plane029.geometry}
        material={materials.leaves}
        position={[38.769, 4.892, 33.7]}
        rotation={[-0.98, 0.185, -1.078]}
      />
      <mesh
        geometry={nodes.Plane030.geometry}
        material={materials["leaves.003"]}
        position={[35.729, 5.275, 36.784]}
        rotation={[-0.877, 0.304, -1.279]}
      />
      <mesh
        geometry={nodes.Plane031.geometry}
        material={materials["leaves.002"]}
        position={[45.259, 6.992, -20.164]}
        rotation={[-1.983, 0.09, -2.79]}
      />
      <mesh
        geometry={nodes.Plane032.geometry}
        material={materials["leaves.003"]}
        position={[3.808, 15.185, -37.128]}
        rotation={[-2.299, -0.542, -2.837]}
      />
      <mesh
        geometry={nodes.Plane033.geometry}
        material={materials.leaves}
        position={[-21.587, 26.305, -3.458]}
        rotation={[-2.418, -0.783, 3.024]}
      />
      <mesh
        geometry={nodes.Plane034.geometry}
        material={materials["leaves.002"]}
        position={[-10.739, 7.506, 40.066]}
        rotation={[-1.738, -0.604, -3.084]}
      />
      <mesh
        geometry={nodes.Plane035.geometry}
        material={materials.leaves}
        position={[-30.061, 6.426, 38.854]}
        rotation={[-1.738, -0.604, -3.084]}
      />
      <mesh
        geometry={nodes.Plane036.geometry}
        material={materials.leaves}
        position={[0.303, 6.64, 48.007]}
        rotation={[-1.876, -0.243, -3.11]}
      />
      <mesh
        geometry={nodes.Plane037.geometry}
        material={materials.leaves}
        position={[-36.593, 7.299, 21.684]}
        rotation={[-1.703, -0.708, -2.807]}
      />
      <mesh
        geometry={nodes.Plane038.geometry}
        material={materials["leaves.002"]}
        position={[15.898, 30.14, 21.216]}
        rotation={[-1.132, 0.181, -1.133]}
      />
      <mesh
        geometry={nodes.Plane039.geometry}
        material={materials["leaves.003"]}
        position={[14.791, 56.284, -2.548]}
        rotation={[-1.513, 0.628, -0.23]}
      />
      <mesh
        geometry={nodes.Plane040.geometry}
        material={materials.leaves}
        position={[6.489, 57.214, -5.198]}
        rotation={[-1.516, 0.618, -0.334]}
      />
      <mesh
        geometry={nodes.Plane041.geometry}
        material={materials["leaves.003"]}
        position={[1.06, 53.106, 12.243]}
        rotation={[-1.009, -0.04, -0.099]}
      />
      <mesh
        geometry={nodes.Plane042.geometry}
        material={materials["leaves.002"]}
        position={[23.816, 7.523, -43.555]}
        rotation={[-1.434, -0.115, -0.849]}
      />
      <mesh
        geometry={nodes.Plane043.geometry}
        material={materials["leaves.002"]}
        position={[41.158, 4.259, -47.027]}
        rotation={[-1.434, -0.115, -0.849]}
      />
      <mesh
        geometry={nodes.Plane044.geometry}
        material={materials.leaves}
        position={[24.246, 5.325, 47.331]}
        rotation={[-1.122, 0.046, -0.979]}
      />
      <mesh
        geometry={nodes.Plane045.geometry}
        material={materials["leaves.001"]}
        position={[-36.513, 3.873, -48.694]}
        rotation={[-2.168, 0.011, 2.874]}
      />
      <mesh
        geometry={nodes.Plane046.geometry}
        material={materials["leaves.002"]}
        position={[-58.574, 4.84, -14.182]}
        rotation={[-2.168, 0.011, 2.874]}
      />
      <mesh
        geometry={nodes.Plane047.geometry}
        material={materials["leaves.002"]}
        position={[-58.4, 4.889, -14.386]}
        rotation={[-1.034, 0.233, 0.35]}
      />
      <mesh
        geometry={nodes.Plane048.geometry}
        material={materials["leaves.002"]}
        position={[52.579, 5.74, -24.321]}
        rotation={[-1.305, 0.662, 0.083]}
      />
      <mesh
        geometry={nodes.Plane049.geometry}
        material={materials.leaves}
        position={[52.261, 5.967, -24.149]}
        rotation={[-2.081, 0.317, 3.003]}
      />
      <mesh
        geometry={nodes.Plane050.geometry}
        material={materials["leaves.001"]}
        position={[59.041, 3.957, -4.829]}
        rotation={[-1.398, 0.59, 0.044]}
      />
      <mesh
        geometry={nodes.Plane051.geometry}
        material={materials["leaves.002"]}
        position={[59.059, 3.715, -6.466]}
        rotation={[-2.259, -0.44, 2.857]}
      />
      <mesh
        geometry={nodes.Plane052.geometry}
        material={materials.leaves}
        position={[32.543, 4.969, -48.31]}
        rotation={[-2.016, 0.668, 1.46]}
      />
      <mesh
        geometry={nodes.Plane053.geometry}
        material={materials["leaves.001"]}
        position={[30.468, 4.581, -47.728]}
        rotation={[-1.773, -0.994, -1.748]}
      />
      <mesh
        geometry={nodes.Plane054.geometry}
        material={materials["leaves.003"]}
        position={[-13.764, 5.772, -54.865]}
        rotation={[-1.402, -0.343, -1.173]}
      />
      <mesh
        geometry={nodes.Plane055.geometry}
        material={materials["leaves.001"]}
        position={[8.805, 56.891, -5.171]}
        rotation={[-2.168, 0.011, 2.874]}
      />
      <mesh
        geometry={nodes.Plane056.geometry}
        material={materials["leaves.001"]}
        position={[13.105, 56.324, -3.126]}
        rotation={[-2.189, -0.169, 1.99]}
      />
      <mesh
        geometry={nodes.Plane057.geometry}
        material={materials["leaves.003"]}
        position={[20.643, 5.802, -47.337]}
        rotation={[-2.139, -0.268, -1.997]}
      />
      <mesh
        geometry={nodes.Plane058.geometry}
        material={materials["leaves.001"]}
        position={[23.623, 7.113, -47.044]}
        rotation={[-1.834, -0.457, -1.625]}
      />
      <mesh
        geometry={nodes.Plane059.geometry}
        material={materials["leaves.003"]}
        position={[-33.888, 7.114, 28.823]}
        rotation={[-1.522, -0.654, -1.86]}
      />
      <mesh
        geometry={nodes.Plane060.geometry}
        material={materials["leaves.003"]}
        position={[-22.955, 5.184, 48.424]}
        rotation={[-1.926, -0.336, -3.08]}
      />
      <mesh
        geometry={nodes.Plane061.geometry}
        material={materials["leaves.001"]}
        position={[-2.15, 5.398, 53.314]}
        rotation={[-1.836, 0.542, 1.579]}
      />
      <mesh
        geometry={nodes.Plane062.geometry}
        material={materials["leaves.002"]}
        position={[18.965, 13.407, -31.976]}
        rotation={[-1.899, -0.478, -2.392]}
      />
      <mesh
        geometry={nodes.Plane063.geometry}
        material={materials["leaves.002"]}
        position={[12.389, 6.316, -48.856]}
        rotation={[-1.742, -0.399, -2.082]}
      />
      <mesh
        geometry={nodes.Plane064.geometry}
        material={materials["leaves.002"]}
        position={[26.469, 4.413, -48.073]}
        rotation={[-1.925, -0.589, -2.247]}
      />
      <mesh
        geometry={nodes.Plane065.geometry}
        material={materials["leaves.001"]}
        position={[-10.814, 5.394, -61.04]}
        rotation={[-1.886, 0.21, 1.847]}
      />
      <mesh
        geometry={nodes.Plane066.geometry}
        material={materials["leaves.002"]}
        position={[-45.324, 5.215, -36.725]}
        rotation={[-1.661, -0.873, -1.907]}
      />
      <mesh
        geometry={nodes.Plane067.geometry}
        material={materials["leaves.001"]}
        position={[-48.484, 5.239, -35.095]}
        rotation={[-1.084, -0.362, -0.841]}
      />
      <mesh
        geometry={nodes.Plane068.geometry}
        material={materials.leaves}
        position={[-51.006, 5.333, -30.611]}
        rotation={[-1.286, -0.322, -1.147]}
      />
      <mesh
        geometry={nodes.Plane069.geometry}
        material={materials["leaves.001"]}
        position={[0.538, 16.216, -36.681]}
        rotation={[-1.886, 0.21, 1.847]}
      />
      <mesh
        geometry={nodes.Plane070.geometry}
        material={materials["leaves.001"]}
        position={[0.748, 16.085, -36.309]}
        rotation={[-1.243, -0.19, -1.233]}
      />
      <mesh
        geometry={nodes.Plane071.geometry}
        material={materials["leaves.001"]}
        position={[4.544, 18.227, -34.824]}
        rotation={[-1.457, 0.102, -1.097]}
      />
      <mesh
        geometry={nodes.Plane072.geometry}
        material={materials.leaves}
        position={[9.734, 11.059, -42.154]}
        rotation={[-2.056, -0.085, -1.866]}
      />
      <mesh
        geometry={nodes.Plane073.geometry}
        material={materials["leaves.002"]}
        position={[29.273, 4.271, -48.337]}
        rotation={[-2.016, 0.693, 1.343]}
      />
      <mesh
        geometry={nodes.Cube071.geometry}
        material={materials["rocks.001"]}
        position={[-7.92, 42.512, -14.247]}
        rotation={[-0.344, -0.726, -0.059]}
      />
      <mesh
        geometry={nodes.Plane074.geometry}
        material={materials.leaves}
        position={[-11.218, 41.798, -9.622]}
        rotation={[-2.217, -0.744, 3.05]}
      />
      <mesh
        geometry={nodes.Plane075.geometry}
        material={materials.leaves}
        position={[-7.377, 40.132, -16.648]}
        rotation={[-2.651, -0.1, 2.52]}
      />
      <mesh
        geometry={nodes.Plane076.geometry}
        material={materials["leaves.001"]}
        position={[20.798, 8.736, -42.659]}
        rotation={[-1.834, -0.457, -1.625]}
      />
      <mesh
        geometry={nodes.Plane077.geometry}
        material={materials["leaves.001"]}
        position={[-5.961, 39.822, -17.901]}
        rotation={[-1.462, -0.184, -1.79]}
      />
      <mesh
        geometry={nodes.Plane078.geometry}
        material={materials["leaves.001"]}
        position={[-5.971, 39.752, -17.655]}
        rotation={[-2.061, -0.4, 3.14]}
      />
      <mesh
        geometry={nodes.Plane079.geometry}
        material={materials["leaves.003"]}
        position={[9.62, 56.722, -3.969]}
        rotation={[-1.513, 0.628, -0.23]}
      />
      <mesh
        geometry={nodes.Plane080.geometry}
        material={materials["leaves.002"]}
        position={[-10.921, 21.643, -25.411]}
        rotation={[-1.205, -0.237, -0.644]}
      />
      <mesh
        geometry={nodes.Plane081.geometry}
        material={materials["leaves.001"]}
        position={[-10.642, 21.493, -26.884]}
        rotation={[-2.168, 0.011, 2.874]}
      />
      <mesh
        geometry={nodes.Plane082.geometry}
        material={materials["leaves.002"]}
        position={[-10.873, 20.337, -28.214]}
        rotation={[-2.79, 0.055, 2.912]}
      />
      <mesh
        geometry={nodes.Plane083.geometry}
        material={materials["leaves.001"]}
        position={[-10.593, 21.007, -27.401]}
        rotation={[-1.808, 0.23, 0.112]}
      />
      <mesh
        geometry={nodes.Plane084.geometry}
        material={materials["leaves.003"]}
        position={[-8.185, 21.247, -26.98]}
        rotation={[-2.489, -0.345, -2.571]}
      />
      <mesh
        geometry={nodes.Plane085.geometry}
        material={materials["leaves.003"]}
        position={[-24.578, 25.59, -2.266]}
        rotation={[-2.343, -0.713, -2.832]}
      />
      <mesh
        geometry={nodes.Plane086.geometry}
        material={materials["leaves.003"]}
        position={[12.582, 7.11, 46.061]}
        rotation={[-1.445, -0.26, -2.675]}
      />
      <mesh
        geometry={nodes.Plane087.geometry}
        material={materials["leaves.003"]}
        position={[60.024, 3.499, -4.444]}
        rotation={[-1.445, -0.26, -2.675]}
      />
      <mesh
        geometry={nodes.Plane088.geometry}
        material={materials["leaves.002"]}
        position={[-15.166, 4.273, -63.23]}
        rotation={[-1.642, -0.598, -2.214]}
      />
      <mesh
        geometry={nodes.Plane089.geometry}
        material={materials["leaves.002"]}
        position={[-16.151, 4.328, -62.761]}
        rotation={[-1.642, -0.598, -2.214]}
      />
      <mesh
        geometry={nodes.Mball065.geometry}
        material={materials["rocks.001"]}
        position={[-16.976, 4.695, -60.977]}
        rotation={[-0.493, -1.084, -0.221]}
      />
      <mesh
        geometry={nodes.Plane090.geometry}
        material={materials["leaves.001"]}
        position={[-24.428, 4.471, -58.969]}
        rotation={[-1.974, 0.454, 2.091]}
      />
      <mesh
        geometry={nodes.Plane091.geometry}
        material={materials["leaves.002"]}
        position={[-25.194, 5.05, -52.855]}
        rotation={[-1.661, -0.873, -1.907]}
      />
      <mesh
        geometry={nodes.Plane092.geometry}
        material={materials["leaves.001"]}
        position={[-6.714, 49.423, -10.06]}
        rotation={[-1.568, -0.533, -1.719]}
      />
      <mesh
        geometry={nodes.Plane093.geometry}
        material={materials.leaves}
        position={[-7.595, 49.345, -8.653]}
        rotation={[-2.145, -0.62, -3.089]}
      />
      <mesh
        geometry={nodes.Plane094.geometry}
        material={materials.leaves}
        position={[-2.951, 56.141, -8.219]}
        rotation={[-1.523, -0.406, -0.993]}
      />
      <mesh
        geometry={nodes.Plane095.geometry}
        material={materials["leaves.003"]}
        position={[-4.485, 56.352, -6.66]}
        rotation={[-2.343, -0.713, -2.832]}
      />
      <mesh
        geometry={nodes.Plane096.geometry}
        material={materials.leaves}
        position={[-11.652, 41.334, -12.055]}
        rotation={[-1.372, -0.173, -1.041]}
      />
      <mesh
        geometry={nodes.Plane097.geometry}
        material={materials.leaves}
        position={[-12.436, 41.462, -12.38]}
        rotation={[-2.12, -0.08, 2.27]}
      />
      <mesh
        geometry={nodes.Cube072.geometry}
        material={materials["Material.005"]}
        position={[25.329, 35.504, 0.393]}
        rotation={[-2.9, -1.301, -2.974]}
      />
      <mesh
        geometry={nodes.Cube073.geometry}
        material={materials["Material.005"]}
        position={[-17.075, 28.071, -11.007]}
        rotation={[-0.064, 0.098, -0.059]}
      />
      <mesh
        geometry={nodes.Cube074.geometry}
        material={materials["Material.005"]}
        position={[-20.796, 11.205, -33.533]}
        rotation={[0.055, 0.194, -0.386]}
      />
      <mesh
        geometry={nodes.Cube075.geometry}
        material={materials["Material.005"]}
        position={[-23.165, 10.91, -31.154]}
        rotation={[-1.93, -1.299, 1.32]}
      />
      <mesh
        geometry={nodes.Mball066.geometry}
        material={materials["rocks.001"]}
        position={[-29.58, 6.515, -36.673]}
        rotation={[-2.855, 0.671, -3.101]}
      />
      <mesh
        geometry={nodes.Plane098.geometry}
        material={materials["leaves.003"]}
        position={[-28.396, 7.683, -31.766]}
        rotation={[-1.073, -0.447, -1.041]}
      />
      <mesh
        geometry={nodes.Plane099.geometry}
        material={materials["leaves.002"]}
        position={[-32.817, 5.021, -38.095]}
        rotation={[-1.661, -0.873, -1.907]}
      />
      <mesh
        geometry={nodes.Cube076.geometry}
        material={materials["Material.005"]}
        position={[-10.249, 29.189, 18.484]}
        rotation={[-3.077, 0.119, 3.069]}
      />
      <mesh
        geometry={nodes.Cube077.geometry}
        material={materials["Material.005"]}
        position={[43.473, 7.897, 4.602]}
        rotation={[-2.849, -1.243, -3.065]}
      />
      <mesh
        geometry={nodes.Cube078.geometry}
        material={materials["Material.005"]}
        position={[-37.185, 11.093, -10.091]}
        rotation={[-0.116, 0.637, -0.132]}
      />
      <mesh
        geometry={nodes.Cube079.geometry}
        material={materials["Material.005"]}
        position={[14.486, 52.469, -7.003]}
        rotation={[2.93, -1.127, 2.734]}
      />
      <mesh
        geometry={nodes.Plane100.geometry}
        material={materials["leaves.003"]}
        position={[-15.447, 32.914, -12.668]}
        rotation={[-2.418, -0.696, -2.912]}
      />
      <mesh
        geometry={nodes.Cube080.geometry}
        material={materials["Material.005"]}
        position={[-11.442, -1.91, -80.67]}
        rotation={[-0.206, 0.344, -0.052]}
      />
      <mesh
        geometry={nodes.Plane101.geometry}
        material={materials["leaves.001"]}
        position={[-0.81, 7.07, -54.163]}
        rotation={[-2.057, -0.339, 3.058]}
      />
      <mesh
        geometry={nodes.Plane102.geometry}
        material={materials["leaves.002"]}
        position={[-2.282, 6.378, -55.41]}
        rotation={[-1.85, -0.402, -2.235]}
      />
      <mesh
        geometry={nodes.Plane103.geometry}
        material={materials["leaves.001"]}
        position={[-4.255, 6.391, -56.83]}
        rotation={[-2.057, -0.339, 3.058]}
      />
      <mesh
        geometry={nodes.Plane104.geometry}
        material={materials["leaves.002"]}
        position={[4.594, 5.013, -53.781]}
        rotation={[-1.937, -0.262, -2.313]}
      />
      <mesh
        geometry={nodes.Mball067.geometry}
        material={materials["rocks.001"]}
        position={[-46.568, 5.436, -31.592]}
        rotation={[-2.855, 0.671, -3.101]}
      />
      <mesh
        geometry={nodes.Plane105.geometry}
        material={materials.leaves}
        position={[-47.259, 6.681, -31.966]}
        rotation={[-1.286, -0.322, -1.147]}
      />
      <mesh
        geometry={nodes.Cube083.geometry}
        material={materials["Material.005"]}
        position={[15.132, 39.186, -14.855]}
        rotation={[0.313, -1.274, 0.085]}
      />
      <mesh
        geometry={nodes.Plane106.geometry}
        material={materials.leaves}
        position={[-59.394, 5.428, 15.221]}
        rotation={[-2.135, -0.309, 2.527]}
      />
      <mesh
        geometry={nodes.Plane107.geometry}
        material={materials.leaves}
        position={[-49.015, 6.153, 18.792]}
        rotation={[-1.324, -0.359, -1.111]}
      />
      <mesh
        geometry={nodes.Plane108.geometry}
        material={materials["leaves.002"]}
        position={[-54.79, 5, 4.829]}
        rotation={[-0.996, 0.324, -0.279]}
      />
      <group
        position={[-16.418, 6.649, -57.221]}
        rotation={[-0.159, -0.14, 0.147]}
      >
        <mesh
          geometry={nodes.Plane111_1.geometry}
          material={materials.flower}
        />
        <mesh
          geometry={nodes.Plane111_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane111_3.geometry}
          material={materials["leaves.002"]}
        />
        <mesh
          geometry={nodes.Plane111_4.geometry}
          material={materials["leaves.001"]}
        />
      </group>
      <group
        position={[-0.427, 5.5, -56.782]}
        rotation={[-0.543, 0.305, 0.056]}
      >
        <mesh
          geometry={nodes.Plane113_1.geometry}
          material={materials["flower.002"]}
        />
        <mesh
          geometry={nodes.Plane113_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane113_3.geometry}
          material={materials["leaves.002"]}
        />
        <mesh
          geometry={nodes.Plane113_4.geometry}
          material={materials["leaves.001"]}
        />
      </group>
      <group
        position={[25.178, 5.377, -46.814]}
        rotation={[-0.694, 0.692, 0.365]}
      >
        <mesh
          geometry={nodes.Plane114_1.geometry}
          material={materials.flower}
        />
        <mesh
          geometry={nodes.Plane114_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane114_3.geometry}
          material={materials["leaves.002"]}
        />
        <mesh
          geometry={nodes.Plane114_4.geometry}
          material={materials["leaves.001"]}
        />
      </group>
      <group
        position={[11.83, 56.32, -3.564]}
        rotation={[-0.694, 0.692, 0.365]}
      >
        <mesh
          geometry={nodes.Plane115_1.geometry}
          material={materials.flower}
        />
        <mesh
          geometry={nodes.Plane115_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane115_3.geometry}
          material={materials["leaves.002"]}
        />
        <mesh
          geometry={nodes.Plane115_4.geometry}
          material={materials["leaves.001"]}
        />
      </group>
      <group
        position={[-12.948, 41.929, -9.037]}
        rotation={[-0.386, 0.5, 0.482]}
      >
        <mesh
          geometry={nodes.Plane116_1.geometry}
          material={materials["flower.001"]}
        />
        <mesh
          geometry={nodes.Plane116_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane116_3.geometry}
          material={materials["leaves.002"]}
        />
        <mesh
          geometry={nodes.Plane116_4.geometry}
          material={materials["leaves.001"]}
        />
      </group>
      <group
        position={[-3.955, 56.529, -6.364]}
        rotation={[-0.386, 0.5, 0.482]}
      >
        <mesh
          geometry={nodes.Plane117_1.geometry}
          material={materials["flower.001"]}
        />
        <mesh
          geometry={nodes.Plane117_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane117_3.geometry}
          material={materials["leaves.002"]}
        />
        <mesh
          geometry={nodes.Plane117_4.geometry}
          material={materials["leaves.001"]}
        />
      </group>
      <group
        position={[-7.668, 49.339, -9.981]}
        rotation={[-0.667, 0.286, 0.771]}
      >
        <mesh
          geometry={nodes.Plane118_1.geometry}
          material={materials["flower.001"]}
        />
        <mesh
          geometry={nodes.Plane118_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane118_3.geometry}
          material={materials["leaves.002"]}
        />
        <mesh
          geometry={nodes.Plane118_4.geometry}
          material={materials["leaves.001"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane116.geometry}
        material={materials["leaves.001"]}
        position={[62.544, -0.2, 4.47]}
        rotation={[-0.761, 0.476, -0.07]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.butter}
        position={[1.61, 7.889, -58.279]}
        rotation={[-0.835, -0.503, 0.149]}
      />
      <mesh
        geometry={nodes.Plane117.geometry}
        material={materials.flower}
        position={[6.317, 10.578, -58.455]}
        rotation={[-1.215, -0.525, 0.164]}
      />
      <mesh
        geometry={nodes.Plane118.geometry}
        material={materials["flower.001"]}
        position={[-14.584, 10.247, -58.696]}
        rotation={[-1.215, -0.525, 0.164]}
      />
    </a.group>
  );
}

useGLTF.preload(fantasy);
